services:

  frontend:

    image:
      NavozZ/portfolio-frontend:latest

    ports:
      - "80:80"

  backend:

    image:
      NavozZ/portfolio-backend:latest

    ports:
      - "5000:5000"

    env_file:
      - .env
